// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvF7RJZ30eSW15G8R1YmOiLMbkfmqAlNg',
    appId: '1:260911985312:web:65212829332e1fda334fc5',
    messagingSenderId: '260911985312',
    projectId: 'clickaeventsp',
    authDomain: 'clickaeventsp.firebaseapp.com',
    storageBucket: 'clickaeventsp.appspot.com',
    measurementId: 'G-VDMHJ9ZBPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_suAvNmgfVEi-8CMIH1qqDWF3lZDxkgY',
    appId: '1:260911985312:android:7789f4d940818c98334fc5',
    messagingSenderId: '260911985312',
    projectId: 'clickaeventsp',
    storageBucket: 'clickaeventsp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0HF2-ad-8T5xxvq7YaltHmuRYETmaCJE',
    appId: '1:260911985312:ios:89ea1aad0ad8af5d334fc5',
    messagingSenderId: '260911985312',
    projectId: 'clickaeventsp',
    storageBucket: 'clickaeventsp.appspot.com',
    iosBundleId: 'com.jakir.clickaeventsp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0HF2-ad-8T5xxvq7YaltHmuRYETmaCJE',
    appId: '1:260911985312:ios:ad799e2f55db8b5e334fc5',
    messagingSenderId: '260911985312',
    projectId: 'clickaeventsp',
    storageBucket: 'clickaeventsp.appspot.com',
    iosBundleId: 'com.jakir.clickaeventsp.RunnerTests',
  );
}
